import assert from 'node:assert/strict';
import crypto from 'node:crypto';
import {createRequire} from 'node:module';
import {initializeApp,deleteApp} from 'firebase-admin/app';
import {getAuth} from 'firebase-admin/auth';
import {getFirestore} from 'firebase-admin/firestore';
import {getRemoteConfig} from 'firebase-admin/remote-config';
const require=createRequire(import.meta.url),{chromium}=require('C:/Users/This PC/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
if(!process.argv.includes('--live'))throw new Error('Pass --live for disposable production QA');
const app=initializeApp({projectId:'campusmate-7f1ab'}),auth=getAuth(app),db=getFirestore(app),tag='admin-qa-ext-'+Date.now(),actor=tag+'-admin',uid=tag+'-user',password=crypto.randomBytes(24).toString('base64url')+'Aa1!';
let browser,page;
try{
 await auth.createUser({uid:actor,email:actor+'@example.test',password,emailVerified:true});await auth.setCustomUserClaims(actor,{admin:true});await auth.createUser({uid,email:uid+'@example.test',emailVerified:true});
 await db.doc('users/'+uid).set({id:uid,name:'QA detailed extensions',faculty:'QA extensions faculty',studentId:'9999999999',bio:'QA detailed profile text',isDiscoverable:false,notificationsEnabled:true,avatarUri:'https://campusmate-7f1ab.web.app/brand-icon.png',gallery:['https://campusmate-7f1ab.web.app/brand-icon.png'],activities:['running'],matchingPreferences:{ageMin:18,ageMax:35},spotifyTokens:{accessToken:'QA_SECRET_NOT_VISIBLE'}});
 const originalRemote=(await getRemoteConfig(app).getTemplate()).parameters.enable_feature_call.defaultValue.value;
 browser=await chromium.launch();page=await browser.newPage({viewport:{width:1440,height:1000}});const errors=[];page.on('pageerror',e=>errors.push(e.message));let cancel=false;page.on('dialog',async d=>{if(cancel){cancel=false;await d.dismiss();}else await d.accept();});
 let settingsWrites=0;page.on('request',r=>{if(r.url().endsWith('/adminConsole')&&r.method()==='POST'){const op=r.postDataJSON()?.data?.op;if(['saveRemoteParameters','saveOperations'].includes(op))settingsWrites++;}});
 await page.goto('https://campusmate-7f1ab.web.app/admin.html');await page.getByLabel('อีเมล',{exact:true}).fill(actor+'@example.test');await page.getByLabel('รหัสผ่าน',{exact:true}).fill(password);await page.getByRole('button',{name:'เข้าสู่ระบบ',exact:true}).click();await page.getByText('ดูแลชุมชนให้ปลอดภัย').waitFor();
 const full=(await page.locator('aside').boundingBox()).width;await page.getByRole('button',{name:'ย่อแถบเมนู'}).click();assert.ok((await page.locator('aside').boundingBox()).width<full);await page.reload();await page.getByRole('button',{name:'ขยายแถบเมนู'}).waitFor();await page.getByRole('button',{name:'ขยายแถบเมนู'}).click();
 await page.locator('nav').getByRole('button',{name:'ผู้ใช้และอีเมล'}).click();await page.locator('.user-directory').getByText(/โหลดครบแล้ว/).waitFor({timeout:60000});const target=page.locator(`tr[data-uid="${uid}"]`);await target.waitFor();assert.ok(await page.locator('.directory-table tbody tr').count()>=2);
 await page.screenshot({path:'artifacts/admin-all-users.png',fullPage:true});await page.getByLabel('ค้นหาในรายชื่อ').fill('QA detailed extensions');assert.equal(await page.locator('.directory-table tbody tr').count(),1);await target.getByRole('button',{name:'ดูโปรไฟล์'}).click();await page.getByRole('heading',{name:'QA detailed extensions',exact:true}).waitFor();await page.getByText('QA detailed profile text',{exact:true}).waitFor();assert.equal((await page.locator('body').innerText()).includes('QA_SECRET_NOT_VISIBLE'),false);
 await page.waitForFunction(()=>{const img=document.querySelector('.profile-gallery img');return img?.complete&&img.naturalWidth>0;});await page.getByRole('button',{name:'ขยายรูปภาพที่แนบในรายงาน'}).click();await page.getByRole('dialog').waitFor();await page.getByRole('button',{name:'ปิดรูปภาพ',exact:true}).click();await page.screenshot({path:'artifacts/admin-detailed-user-profile.png',fullPage:true});
 await page.getByRole('button',{name:'ส่งแจ้งเตือนให้ผู้ใช้นี้'}).click();assert.equal(await page.getByLabel('UID ผู้รับ (คั่นด้วย , หรือขึ้นบรรทัดใหม่)').inputValue(),uid);await page.getByLabel('หัวข้อแจ้งเตือน',{exact:true}).fill('QA custom announcement');await page.getByLabel('ข้อความแจ้งเตือน',{exact:true}).fill('QA no external Push sent');await page.getByRole('button',{name:'ตรวจผู้รับและสร้างตัวอย่าง'}).click();await page.getByText('ไม่มีอุปกรณ์รับ Push ในกลุ่มนี้',{exact:false}).waitFor();
 cancel=true;await page.getByRole('button',{name:'ยืนยันส่งแจ้งเตือน'}).click();assert.equal((await db.doc('accountRestrictions/'+uid).get()).exists,false);await page.getByRole('button',{name:'ยืนยันส่งแจ้งเตือน'}).click();await page.getByRole('status').filter({hasText:'บันทึกประกาศ 1 บัญชี'}).waitFor({timeout:60000});assert.equal((await db.doc('accountRestrictions/'+uid).get()).data().latestAnnouncement.title,'QA custom announcement');await page.screenshot({path:'artifacts/admin-custom-notifications.png',fullPage:true});
 await page.locator('nav').getByRole('button',{name:'การตั้งค่าระบบ'}).click();await page.getByLabel('เพดานผู้รับต่อการส่งประกาศ').waitFor();cancel=true;await page.getByRole('button',{name:'บันทึกนโยบายการส่ง',exact:true}).click();
 const toggle=page.getByLabel('ค่าปริยาย enable_feature_call',{exact:true});await toggle.selectOption(originalRemote==='true'?'false':'true');await page.getByRole('button',{name:'ตรวจค่ากับ Firebase',exact:true}).click();await page.getByRole('status').filter({hasText:'Firebase ตรวจค่าพารามิเตอร์ผ่านแล้ว'}).waitFor({timeout:60000});cancel=true;await page.getByRole('button',{name:'เผยแพร่ค่าที่ตรวจผ่านแล้ว',exact:true}).click();assert.equal(settingsWrites,0);assert.equal((await getRemoteConfig(app).getTemplate()).parameters.enable_feature_call.defaultValue.value,originalRemote);await page.screenshot({path:'artifacts/admin-detailed-settings.png',fullPage:true});
 await page.setViewportSize({width:390,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.locator('nav').getByRole('button',{name:'ผู้ใช้และอีเมล'}).click();await page.locator('.user-directory').getByText(/โหลดครบแล้ว/).waitFor();assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.screenshot({path:'artifacts/admin-directory-mobile.png',fullPage:true});assert.equal(errors.length,0);
 console.log(JSON.stringify({passed:true,flows:['allUsersBeforeSearch','localNameSearch','detailedProfile','galleryExpand','secretExcluded','sidebarCollapse','collapsePersists','targetFromProfile','notificationPreview','cancelNotification','deployedAnnouncementPersistence','notificationHistory','operationalSettings','remoteFirebaseValidation','cancelSettingsPublish','mobile'],settingsWrites,externalNotificationsSent:0,realUserDataChanged:false,errors}));
}catch(e){if(page){await page.screenshot({path:'artifacts/admin-extensions-failure.png',fullPage:true});console.error((await page.locator('body').innerText()).slice(-2400));}throw e;}
finally{
 await browser?.close();await db.doc('users/'+uid).delete();await db.doc('accountRestrictions/'+uid).delete();for(const account of [actor,uid]){await auth.deleteUser(account).catch(()=>{});await db.doc('profiles/'+account).delete();await db.doc('discoveryProfiles/'+account).delete();}
 for(const collection of ['adminNotificationJobs','adminNotificationPreviews','adminAudit']){const docs=await db.collection(collection).where('actor','==',actor).get();for(const doc of docs.docs)await doc.ref.delete();}await db.doc('adminNotificationLocks/'+actor).delete();await db.terminate();await deleteApp(app);
}
