allowBuilds:
  '@firebase/util': true
  protobufjs: true
minimumReleaseAgeExclude:
  - '@expo/cli@57.0.20'
  - '@expo/env@2.4.3'
  - '@expo/fingerprint@0.20.11'
  - '@expo/metro-config@57.0.12'
  - expo-constants@57.0.16 || 57.0.17
  - expo-font@57.0.2
  - expo@57.0.18
  - expo-notifications@57.0.16
  - expo-eas-client@57.0.3
  - expo-updates@57.0.21
