plugins {
  id 'com.android.library'
  id 'expo-module-gradle-plugin'
}
group = 'expo.modules.chatvideoprocessor'
version = '1.0.0'
android {
  namespace 'expo.modules.chatvideoprocessor'
  defaultConfig {
    versionCode 1
    versionName '1.0.0'
  }
}
dependencies {
  implementation 'androidx.media3:media3-transformer:1.9.0'
  implementation 'androidx.media3:media3-effect:1.9.0'
}
