import Text from './AppText';
import React from 'react';
import { Platform, StyleSheet } from 'react-native';
import Ionicons from '@expo/vector-icons/Ionicons';
import { SymbolView } from 'expo-symbols';

const ANDROID_ICON_MAP = {
  'arrow.counterclockwise': 'arrow-undo',
  'arrow.down': 'arrow-down',
  'arrow.down.circle': 'arrow-down-circle-outline',
  'arrow.down.circle.fill': 'arrow-down-circle',
  'arrow.down.to.line': 'download-outline',
  'arrow.down.right.and.arrow.up.left': 'contract',
  'arrow.left': 'arrow-back',
  'arrow.left.and.right.righttriangle.left.righttriangle.right.fill': 'swap-horizontal',
  'arrow.up.right.square': 'open-outline',
  'arrow.up.right.square.fill': 'open',
  pip: 'open-outline',
  'pip.enter': 'open-outline',
  'pip.exit': 'contract-outline',
  'arrow.right': 'arrow-forward',
  'arrow.right.circle.fill': 'arrow-forward-circle',
  'arrow.triangle.2.circlepath': 'sync',
  'arrow.up': 'arrow-up',
  'arrow.up.circle': 'arrow-up-circle-outline',
  'arrow.up.circle.fill': 'arrow-up-circle',
  'arrow.up.left.and.arrow.down.right': 'expand',
  'arrow.uturn.backward': 'arrow-undo',
  'arrow.uturn.backward.circle': 'arrow-undo-circle',
  'arrowshape.turn.up.left': 'return-up-back',
  'arrowshape.turn.up.left.fill': 'return-up-back',
  apps: 'apps',
  'banknote.fill': 'cash',
  bicycle: 'bicycle',
  'chart.bar.fill': 'bar-chart',
  'figure.mind.and.body': 'body',
  'figure.pool.swim': 'water',
  'fork.knife': 'restaurant',
  'gamecontroller.fill': 'game-controller',
  globe: 'globe-outline',
  'music.note': 'musical-notes',
  'paintpalette.fill': 'color-palette',
  'person.3.fill': 'people',
  'point.topleft.down.curvedto.point.bottomright.up': 'trail-sign',
  target: 'locate',
  'bell.badge.fill': 'notifications',
  'bell.fill': 'notifications',
  'bubble.left.fill': 'chatbubble',
  'bubble.left.and.bubble.right.fill': 'chatbubbles',
  'bubble.left.and.exclamationmark.bubble.right': 'chatbubble-ellipses',
  'building.columns.fill': 'business',
  'book.closed.fill': 'book',
  'book.fill': 'book',
  calendar: 'calendar',
  'calendar.badge.clock': 'calendar',
  camera: 'camera',
  'camera.fill': 'camera',
  'camera.filters': 'color-filter',
  checkmark: 'checkmark',
  'checkmark.circle.fill': 'checkmark-circle',
  'checkmark.seal.fill': 'checkmark-circle',
  'chevron.down': 'chevron-down',
  'chevron.left': 'chevron-back',
  'chevron.right': 'chevron-forward',
  'chevron.up': 'chevron-up',
  'chevron.up.chevron.down': 'swap-vertical',
  'circle.fill': 'ellipse',
  'circle.lefthalf.filled': 'contrast',
  clock: 'time',
  'clock.badge.xmark': 'time-outline',
  'clock.fill': 'time',
  'clock.arrow.2.circlepath': 'refresh-circle',
  'cloud.arrow.down.fill': 'cloud-download',
  'cup.and.saucer.fill': 'cafe',
  'doc.on.clipboard': 'clipboard',
  'doc.on.doc': 'copy',
  'doc.text.fill': 'document-text',
  'dumbbell.fill': 'barbell',
  ellipsis: 'ellipsis-horizontal',
  'ellipsis.circle': 'ellipsis-horizontal-circle',
  'envelope.fill': 'mail',
  'eye.fill': 'eye',
  'eye.slash.fill': 'eye-off',
  'exclamationmark.bubble': 'alert-circle-outline',
  'exclamationmark.bubble.fill': 'alert-circle',
  'exclamationmark.circle.fill': 'alert-circle',
  'exclamationmark.triangle': 'warning-outline',
  'exclamationmark.triangle.fill': 'warning',
  'figure.2.and.child.holdinghands': 'people',
  'figure.run.circle.fill': 'walk',
  'figure.run': 'walk',
  'figure.strengthtraining.traditional': 'barbell',
  'face.smiling': 'happy-outline',
  'happy-outline': 'happy-outline',
  smiley: 'happy-outline',
  'flame.fill': 'flame',
  folder: 'folder',
  'folder.fill': 'folder',
  'gearshape.fill': 'settings',
  'graduationcap.fill': 'school',
  'hand.wave.fill': 'hand-left',
  'hand.raised': 'hand-left-outline',
  'hand.raised.fill': 'hand-left',
  'hand.tap.fill': 'finger-print',
  'heart.circle.fill': 'heart-circle',
  'heart.fill': 'heart',
  'heart.slash': 'heart-dislike',
  'info.circle': 'information-circle-outline',
  'info.circle.fill': 'information-circle',
  'crown': 'ribbon-outline',
  'crown.fill': 'ribbon',
  'figure.badminton': 'tennisball',
  'tag': 'pricetag-outline',
  'tag.fill': 'pricetag',
  'leaf.fill': 'leaf',
  lightbulb: 'bulb-outline',
  'lightbulb.fill': 'bulb',
  'line.3.horizontal': 'menu',
  list: 'list',
  'location.circle.fill': 'location',
  'location.fill': 'location',
  'lock.fill': 'lock-closed',
  'lock.shield.fill': 'shield-checkmark',
  'map.fill': 'map',
  magnifyingglass: 'search',
  'mappin.and.ellipse': 'location',
  'mappin.circle.fill': 'location',
  'mappin.slash.circle.fill': 'location-outline',
  'message.fill': 'chatbubble',
  'bubble.left.and.bubble.right': 'chatbubbles',
  mic: 'mic-outline',
  'mic.fill': 'mic',
  'mic.slash.fill': 'mic-off',
  phone: 'call-outline',
  'phone.fill': 'call',
  'phone.down.fill': 'call',
  'phone.badge.plus': 'call-outline',
  'phone.arrow.down.left': 'call-outline',
  'phone.arrow.up.right': 'call-outline',
  video: 'videocam-outline',
  'video.fill': 'videocam',
  'video.slash.fill': 'videocam-off',
  'speaker.wave.3.fill': 'volume-high',
  'speaker.slash.fill': 'volume-mute',
  'camera.rotate.fill': 'camera-reverse',
  'camera.rotate': 'camera-reverse-outline',
  photo: 'image-outline',
  'photo.badge.exclamationmark': 'image-outline',
  'photo.fill': 'image',
  'photo.on.rectangle': 'images',
  'play.fill': 'play',
  'pause.fill': 'pause',
  'rectangle.portrait.and.arrow.right': 'log-out',
  'rotate.right.fill': 'refresh',
  'shield.slash': 'shield-outline',
  'shield.fill': 'shield',
  'shield.lefthalf.filled': 'shield-half-outline',
  'stop.fill': 'square',
  paperplane: 'send',
  'paperplane.fill': 'send',
  pencil: 'pencil',
  'pencil.fill': 'pencil',
  'pencil.circle': 'pencil-outline',
  'pencil.circle.fill': 'pencil',
  'person.2.circle': 'people-circle',
  'person.2.fill': 'people',
  'person.2.slash': 'person-remove',
  'person.badge.plus': 'person-add',
  'person.badge.key.fill': 'key',
  'person.crop.circle.badge.checkmark': 'person-circle',
  'person.crop.circle.badge.plus': 'person-add',
  'person.crop.circle.badge.questionmark': 'help-circle',
  'person.crop.circle.fill': 'person-circle',
  'person.crop.square.fill': 'person',
  'person.fill': 'person',
  'person.text.rectangle.fill': 'person',
  'person.fill.xmark': 'person-remove',
  plus: 'add',
  'quote.bubble.fill': 'chatbox-ellipses',
  search: 'search',
  'slider.horizontal.3': 'options',
  sparkles: 'sparkles',
  speedometer: 'speedometer',
  'sportscourt.fill': 'basketball',
  'square.and.arrow.down': 'download-outline',
  'square.and.arrow.up': 'share',
  'square.and.pencil': 'create',
  'square.fill': 'square',
  'square.grid.2x2.fill': 'grid',
  'square.stack.fill': 'albums',
  'star.fill': 'star',
  'sun.max.fill': 'sunny',
  'sunset.fill': 'sunny',
  'text.bubble': 'chatbox-outline',
  'text.bubble.fill': 'chatbox',
  'text.quote': 'chatbox-ellipses',
  trash: 'trash',
  'trash.fill': 'trash',
  'tray.full.fill': 'file-tray-full',
  tune: 'options',
  'wand.and.stars': 'color-wand',
  'arrow.clockwise': 'sync',
  wifi: 'wifi',
  'wifi.slash': 'cloud-offline',
  xmark: 'close',
  'xmark.circle': 'close-circle',
  'xmark.circle.fill': 'close-circle',

  // Names previously produced by getAndroidSymbol().
  account_balance: 'business',
  account_box: 'person',
  account_circle: 'person-circle',
  add: 'add',
  arrow_back: 'arrow-back',
  arrow_forward: 'arrow-forward',
  arrow_upward: 'arrow-up',
  auto_awesome: 'sparkles',
  cancel: 'close-circle',
  chat: 'chatbox',
  chat_bubble: 'chatbubble',
  check: 'checkmark',
  check_circle: 'checkmark-circle',
  chevron_left: 'chevron-back',
  chevron_right: 'chevron-forward',
  close: 'close',
  directions_run: 'walk',
  event: 'calendar',
  event_available: 'calendar',
  expand_less: 'chevron-up',
  expand_more: 'chevron-down',
  favorite: 'heart',
  fitness_center: 'barbell',
  format_quote: 'chatbox-ellipses',
  forum: 'chatbubbles',
  group: 'people',
  groups: 'people',
  history: 'refresh-circle',
  home: 'home',
  inbox: 'file-tray-full',
  info: 'information-circle',
  local_fire_department: 'flame',
  location_off: 'location-outline',
  location_on: 'location',
  lock: 'lock-closed',
  map: 'map',
  menu: 'menu',
  menu_book: 'book',
  more_horiz: 'ellipsis-horizontal',
  park: 'leaf',
  person: 'person',
  person_add: 'person-add',
  person_off: 'person-remove',
  photo_camera: 'camera',
  schedule: 'time',
  school: 'school',
  search: 'search',
  send: 'send',
  settings: 'settings',
  sports_basketball: 'basketball',
  star: 'star',
  tune: 'options',
  verified_user: 'shield-checkmark',
  warning: 'warning',
  waving_hand: 'hand-left',
};

const IOS_SYMBOL_MAP = {
  'message.fill': 'bubble.left.fill',
  message: 'bubble.left',
  chat_bubble: 'bubble.left.fill',
  chat: 'bubble.left.fill',
  forum: 'bubble.left.and.bubble.right.fill',
  favorite: 'heart.fill',
  group: 'person.2.fill',
  groups: 'person.2.fill',
  event: 'calendar',
  event_available: 'calendar',
  history: 'clock.arrow.2.circlepath',
  cancel: 'xmark.circle.fill',
  check_circle: 'checkmark.circle.fill',
  more_horiz: 'ellipsis',
  settings: 'gearshape.fill',
  search: 'magnifyingglass',
  home: 'house.fill',
  account_circle: 'person.crop.circle.fill',
  account_box: 'person.crop.square.fill',
  close: 'xmark',
  arrow_back: 'arrow.left',
  arrow_forward: 'arrow.right',
  arrow_upward: 'arrow.up',
  check: 'checkmark',
  send: 'paperplane.fill',
  edit: 'pencil',
  delete: 'trash.fill',
  directions_run: 'figure.run',
  fitness_center: 'dumbbell.fill',
  local_fire_department: 'flame.fill',
  location_on: 'mappin.and.ellipse',
  location_off: 'location.slash.fill',
  lock: 'lock.fill',
  menu: 'line.3.horizontal',
  menu_book: 'book.fill',
  photo_camera: 'camera.fill',
  schedule: 'clock.fill',
  school: 'graduationcap.fill',
  sports_basketball: 'sportscourt.fill',
  tune: 'slider.horizontal.3',
  verified_user: 'lock.shield.fill',
  warning: 'exclamationmark.triangle.fill',
  waving_hand: 'hand.wave.fill',
};

function isEmoji(value) {
  return typeof value === 'string' && /[^\x00-\x7F]/.test(value) && !value.includes('.');
}

export function getAndroidIconName(name) {
  return ANDROID_ICON_MAP[name] || 'help-circle-outline';
}

export default function FeatureIcon({ color, name, size = 22, style }) {
  const resolvedName = typeof name === 'object'
    ? (name[Platform.OS] || name.ios || name.android || name.web)
    : name;

  if (isEmoji(resolvedName)) {
    return <Text style={[styles.emoji, { color, fontSize: size, lineHeight: size + 2 }, style]}>{resolvedName}</Text>;
  }

  if (Platform.OS === 'ios') {
    const iosSymbol = IOS_SYMBOL_MAP[resolvedName] || resolvedName;
    return (
      <SymbolView
        name={iosSymbol}
        size={size}
        style={[{ height: size, width: size }, style]}
        tintColor={color}
        fallback={
          <Ionicons
            color={color}
            name={getAndroidIconName(resolvedName)}
            size={size}
            style={[{ height: size, width: size }, style]}
          />
        }
      />
    );
  }

  return (
    <Ionicons
      color={color}
      name={getAndroidIconName(resolvedName)}
      size={size}
      style={[{ height: size, width: size }, style]}
    />
  );
}

const styles = StyleSheet.create({
  emoji: { includeFontPadding: false, textAlign: 'center' },
});
