import {useEffect,useMemo,useState} from 'react';
import {Search,UserRound,Users,ChevronRight,ShieldCheck,Clock} from 'lucide-react';
import {ProfileValue} from './admin-profile-values';
import {ReportMedia} from './report-media';
import {reportMediaSource} from './report-media-policy.mjs';
type Row=Record<string,any>;
export type AdminApi=(op:string,data?:Row)=>Promise<Row>;
const date=(v:any)=>v?new Date(v).toLocaleString('th-TH',{timeZone:'Asia/Bangkok'}):'—';
export function Thumbnail({user}:{user:Row}){const [failed,setFailed]=useState(false),source=reportMediaSource(user.avatarUrl);return <span className="directory-avatar">{source.state==='image'&&!failed?<img src={source.url} alt="รูปโปรไฟล์" loading="lazy" referrerPolicy="no-referrer" onError={()=>setFailed(true)}/>:<UserRound size={23}/>}</span>;}
export function UserDirectory({api,busy,refreshKey,onSelect}:{api:AdminApi;busy:boolean;refreshKey:number;onSelect:(uid:string)=>void}){
 const [rows,setRows]=useState<Row[]>([]),[query,setQuery]=useState(''),[filter,setFilter]=useState('all'),[sort,setSort]=useState('newest'),[loading,setLoading]=useState(true),[error,setError]=useState(''),[retry,setRetry]=useState(0);
 useEffect(()=>{let active=true;setLoading(true);setError('');setRows([]);void(async()=>{try{let cursor:null|string=null;const all:Row[]=[],seen=new Set<string>();do{const response=await api('users',cursor?{cursor}:{});if(!active)return;for(const row of response.rows)if(!seen.has(row.uid)){seen.add(row.uid);all.push(row);}setRows([...all]);cursor=response.cursor;}while(cursor&&active);}catch(e:any){if(active)setError(e.message||'โหลดรายชื่อไม่สำเร็จ');}finally{if(active)setLoading(false);}})();return()=>{active=false;};},[api,refreshKey,retry]);
 const shown=useMemo(()=>{const q=query.trim().toLocaleLowerCase();return rows.filter(r=>(!q||[r.name,r.nickname,r.email,r.uid,r.faculty,r.studentId].some(v=>String(v||'').toLocaleLowerCase().includes(q)))&&(filter==='all'||filter==='active'&&!r.disabled||filter==='suspended'&&r.disabled||filter==='unverified'&&!r.emailVerified||filter==='face_verified'&&r.isFaceVerified||filter==='face_unverified'&&!r.isFaceVerified||filter==='incomplete'&&!r.profileExists)).sort((a,b)=>sort==='name'?String(a.name||a.email).localeCompare(String(b.name||b.email),'th'):new Date(b.createdAt).getTime()-new Date(a.createdAt).getTime());},[rows,query,filter,sort]);
 return <section className="panel user-directory"><div className="panel-heading"><div><h2><Users size={20}/>ผู้ใช้ทั้งหมด <span className="count">{rows.length}</span></h2><p className="small muted">{loading?'กำลังโหลดบัญชีทั้งหมดต่อเนื่อง…':'โหลดครบแล้ว'} · แสดง {shown.length} บัญชี รวมบัญชีที่ยังไม่มีโปรไฟล์</p></div></div><div className="directory-filters"><label>ค้นหาในรายชื่อ<div className="input-icon"><Search size={17}/><input placeholder="ชื่อ อีเมล รหัสนักศึกษา คณะ หรือ UID" value={query} onChange={e=>setQuery(e.target.value)}/></div></label><label>กรองผู้ใช้<select value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">ทุกบัญชี</option><option value="active">ใช้งานได้</option><option value="suspended">ถูกระงับ</option><option value="face_verified">ยืนยันใบหน้าแล้ว</option><option value="face_unverified">ยังไม่ยืนยันใบหน้า</option><option value="unverified">ยังไม่ยืนยันอีเมล</option><option value="incomplete">ยังไม่มีโปรไฟล์</option></select></label><label>เรียงรายชื่อ<select value={sort} onChange={e=>setSort(e.target.value)}><option value="newest">สมัครล่าสุด</option><option value="name">ชื่อผู้ใช้</option></select></label></div>{error&&<div role="alert" className="error">{error}<button onClick={()=>setRetry(retry+1)}>โหลดใหม่</button></div>}<div className="table-scroll directory-table"><table><thead><tr><th>ผู้ใช้ / อีเมล</th><th>คณะ / รหัสนักศึกษา</th><th>สถานะ & ใบหน้า</th><th>สมัครเมื่อ</th><th>โปรไฟล์</th></tr></thead><tbody>{shown.map(r=><tr key={r.uid} data-uid={r.uid}><td><div className="directory-identity"><Thumbnail user={r}/><div><strong>{r.name||'ยังไม่ได้ตั้งชื่อ'}</strong><small>{r.email||r.uid}</small><div style={{display:'flex',gap:6,marginTop:4,flexWrap:'wrap'}}>{r.isAdmin&&<span className="badge reviewing">แอดมิน</span>}{r.isFaceVerified?<span className="badge resolved" style={{fontSize:11,padding:'2px 8px',display:'inline-flex',alignItems:'center',gap:4}}><ShieldCheck size={12}/>ยืนยันหน้า {r.faceMatchScore?`(${r.faceMatchScore}%)`:''}</span>:<span className="badge" style={{fontSize:11,padding:'2px 8px',background:'#f1f5f9',color:'#64748b',display:'inline-flex',alignItems:'center',gap:4}}><Clock size={12}/>ยังไม่ยืนยันหน้า</span>}</div></div></div></td><td>{r.faculty||'—'}<small>{r.studentId||'—'}</small></td><td><span className={'badge '+(r.disabled?'dismissed':'resolved')}>{r.disabled?'ถูกระงับ':'ใช้งานได้'}</span><small>{r.emailVerified?'ยืนยันอีเมลแล้ว':'ยังไม่ยืนยันอีเมล'}</small></td><td>{date(r.createdAt)}</td><td><button disabled={busy} onClick={()=>onSelect(r.uid)}>ดูโปรไฟล์<ChevronRight size={15}/></button></td></tr>)}</tbody></table></div>{!shown.length&&!loading&&<p className="muted">ไม่พบผู้ใช้ตามเงื่อนไขนี้</p>}</section>;
}
const labels:Row={name:'ชื่อ',nickname:'ชื่อเล่น',studentId:'รหัสนักศึกษา',campusEmail:'อีเมลมหาวิทยาลัย',age:'อายุ',gender:'เพศ',faculty:'คณะ',year:'ชั้นปี',bio:'แนะนำตัว',activity:'กิจกรรมหลัก',activities:'กิจกรรมทั้งหมด',activityLabel:'ชื่อกิจกรรม',activityDetails:'รายละเอียดกิจกรรม',skill:'ระดับทักษะ',pace:'เพซ',availability:'เวลาที่สะดวก',availabilitySlots:'ช่วงเวลาที่เลือก',tags:'แท็ก',interests:'ความสนใจ',favoriteTracks:'เพลงโปรด',isDiscoverable:'แสดงในการค้นหาเพื่อน',notificationsEnabled:'เปิดแจ้งเตือน',privacy:'ความเป็นส่วนตัว',matchingPreferences:'เงื่อนไขค้นหาเพื่อน',locationEnabled:'อนุญาตตำแหน่ง',consentAcceptedAt:'ยอมรับข้อตกลงเมื่อ',consentVersion:'เวอร์ชันข้อตกลง',createdAt:'สร้างโปรไฟล์เมื่อ',updatedAt:'แก้ไขโปรไฟล์เมื่อ',lastActiveAt:'กิจกรรมล่าสุด',canCall:'สิทธิ์โทร',isCallTester:'ผู้ทดสอบการโทร',isTester:'ผู้ทดสอบ'};
export function UserProfileDetails({account,onNotify}:{account:Row;onNotify:(uid:string)=>void}){
 const profile=account.profile||{};
 return <section className="panel user-profile-details"><div className="panel-heading"><h2>โปรไฟล์ผู้ใช้แบบละเอียด</h2><button onClick={()=>onNotify(account.uid)}>ส่งแจ้งเตือนให้ผู้ใช้นี้</button></div><div className="profile-stats">{[['รายงานที่ส่ง',account.stats?.reportsMade],['รายงานที่ได้รับ',account.stats?.reportsReceived],['ห้องสนทนาที่เข้าร่วม',account.stats?.conversations]].map(([label,count])=><div key={label}><span>{label}</span><strong>{count??0}</strong></div>)}</div><p className="small muted">{account.profileExists?'มีโปรไฟล์ในระบบ':'บัญชีนี้ยังไม่ได้สร้างโปรไฟล์'} · ช่องทางเข้าสู่ระบบ: {(account.providers||[]).map((p:string)=>p==='password'?'อีเมลและรหัสผ่าน':p==='google.com'?'Google':p).join(', ')||'ไม่ระบุ'} · โหมดการแสดงตัว: {account.visibility?.mode==='incognito'?'ไม่แสดงในการค้นหา':'ปกติ'}</p><dl>{Object.entries(profile).filter(([key])=>key!=='gallery').map(([key,value])=><div key={key}><dt>{labels[key]||key}</dt><dd><ProfileValue value={value} field={key}/></dd></div>)}</dl><h3>รูปแกลเลอรี</h3>{profile.gallery?.length?<div className="profile-gallery">{profile.gallery.map((url:string,i:number)=><ReportMedia key={url+i} url={url}/>)}</div>:<p className="muted">ยังไม่มีรูปแกลเลอรี</p>}<h3>สมาชิก CampusMate Plus</h3>{account.membership?.activeUntil?<dl><div><dt>สถานะปัจจุบัน</dt><dd>{account.membership.activeUntil>Date.now()?'กำลังใช้งาน':'หมดอายุ'}</dd></div><div><dt>หมดอายุ</dt><dd>{date(account.membership.activeUntil)}</dd></div><div><dt>แพ็กเกจ</dt><dd>{account.membership.productId||'—'}</dd></div><div><dt>แหล่งยืนยัน</dt><dd>{account.membership.source||'—'}</dd></div></dl>:<p className="muted">ไม่มีสมาชิกที่ยืนยันในระบบ</p>}{account.restriction?.latestAnnouncement&&<div className="info"><strong>ประกาศล่าสุด: {account.restriction.latestAnnouncement.title}</strong><p>{account.restriction.latestAnnouncement.message}</p></div>}</section>;
}
