import {useEffect,useMemo,useState} from 'react';
import {Search,X} from 'lucide-react';
import {Thumbnail,type AdminApi} from './admin-users';
type Row=Record<string,any>;
export const splitRecipients=(value:string)=>[...new Set(value.split(/[,\n]/).map(v=>v.trim()).filter(Boolean))];
export function UserPicker({api,label,values,onChange,notifications=false,disabled=false}:{api:AdminApi;label:string;values:string[];onChange:(values:string[])=>void;notifications?:boolean;disabled?:boolean}){
 const [rows,setRows]=useState<Row[]>([]),[query,setQuery]=useState(''),[loading,setLoading]=useState(true),[error,setError]=useState(''),[retry,setRetry]=useState(0);
 useEffect(()=>{let active=true;setLoading(true);setError('');setRows([]);void(async()=>{try{let cursor:string|null=null;const all:Row[]=[],seen=new Set();do{const page=await api('users',cursor?{cursor}:{});if(!active)return;for(const row of page.rows)if(!seen.has(row.uid)){seen.add(row.uid);all.push(row);}setRows([...all]);cursor=page.cursor;}while(cursor);}catch(e:any){if(active)setError(e.message||'โหลดรายชื่อไม่ได้');}finally{if(active)setLoading(false);}})();return()=>{active=false;};},[api,retry]);
 const chosen=new Set(values);
 const selected=(row:Row)=>chosen.has(row.uid)||!!row.email&&chosen.has('email:'+row.email.toLowerCase());
 const filtered=useMemo(()=>{const q=query.trim().toLocaleLowerCase();return rows.filter(r=>!q||[r.name,r.nickname,r.email,r.faculty,r.studentId,r.uid].some(v=>String(v||'').toLocaleLowerCase().includes(q))).sort((a,b)=>String(a.name||a.email).localeCompare(String(b.name||b.email),'th'));},[query,rows]);
 const remove=(value:string)=>{const row=rows.find(r=>r.uid===value||'email:'+r.email?.toLowerCase()===value);onChange(values.filter(v=>v!==value&&(!row||v!==row.uid&&v!=='email:'+row.email?.toLowerCase())));};
 const toggle=(row:Row)=>selected(row)?remove(row.uid):onChange([...values,row.uid]);
 return <section className="user-picker" aria-label={label}><h4>{label}</h4><p className="small muted">เลือกได้หลายคน · เลือกแล้ว {values.length} รายการ{loading?' · กำลังโหลดรายชื่อ…':''}</p><div className="picker-selected">{values.map(value=>{const row=rows.find(r=>r.uid===value||'email:'+r.email?.toLowerCase()===value);return <span key={value}>{row?.name||row?.email||(value.startsWith('email:')?value.slice(6):value)}<button type="button" disabled={disabled} aria-label={'นำออก '+(row?.name||row?.email||value)} onClick={()=>remove(value)}><X size={13}/></button></span>;})}</div><label className="picker-search"><span>ค้นหาโปรไฟล์ {label}</span><div className="input-icon"><Search size={16}/><input aria-label={'ค้นหาโปรไฟล์ '+label} placeholder="ชื่อ อีเมล คณะ หรือรหัสนักศึกษา" value={query} onChange={e=>setQuery(e.target.value)}/></div></label>{error&&<div className="error" role="alert">{error}<button type="button" onClick={()=>setRetry(v=>v+1)}>โหลดรายชื่อใหม่</button></div>}<div className="picker-list">{filtered.map(row=><label key={row.uid} className={'picker-person '+(selected(row)?'chosen':'')}><input type="checkbox" aria-label={`เลือก ${row.name||row.email||row.uid} สำหรับ ${label}`} checked={selected(row)} disabled={disabled||notifications&&row.disabled&&!selected(row)} onChange={()=>toggle(row)}/><Thumbnail user={row}/><span><strong>{row.name||'ยังไม่ได้ตั้งชื่อ'}</strong><small>{row.email||row.uid}</small><small>{row.faculty||'ยังไม่ระบุคณะ'}{row.disabled?' · ถูกระงับ':''}</small></span></label>)}</div>{!filtered.length&&!loading&&!error&&<p className="muted">ไม่พบโปรไฟล์ที่ค้นหา</p>}{!loading&&rows.length>0&&<p className="small muted">โหลด {rows.length} บัญชีแล้ว · รายชื่อเดิมที่ไม่พบในระบบยังเก็บไว้จนกว่าจะนำออก</p>}</section>;
}
export function FeatureTesterPicker({api,feature,label,features,onChange,busy}:{api:AdminApi;feature:string;label:string;features:Row;onChange:(next:Row)=>void;busy:boolean}){
 const uidKey='allowed_uids_'+feature,emailKey='allowed_emails_'+feature;
 const values=[...splitRecipients(features[uidKey]||''),...splitRecipients(features[emailKey]||'').map(e=>'email:'+e.toLowerCase())];
 return <><UserPicker api={api} label={'ผู้ทดสอบ '+label} values={values} disabled={busy} onChange={next=>onChange({...features,[uidKey]:next.filter(v=>!v.startsWith('email:')).join(','),[emailKey]:next.filter(v=>v.startsWith('email:')).map(v=>v.slice(6)).join(',')})}/><details className="picker-advanced"><summary>แก้ UID / อีเมลเอง (ขั้นสูง)</summary><label>UID ผู้ทดสอบ (คั่นด้วย ,)<textarea value={features[uidKey]||''} onChange={e=>onChange({...features,[uidKey]:e.target.value})}/></label><label>อีเมลผู้ทดสอบ (คั่นด้วย ,)<textarea value={features[emailKey]||''} onChange={e=>onChange({...features,[emailKey]:e.target.value})}/></label></details></>;
}
